# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme: my_theme
  theme_day: my_theme # original was 'minimal'
  theme_night: my_theme # original was 'minimal'
  #theme_night: true
  font: native
  font_size: L

# SEO

# marketing:
#   seo:
#     site_type: EducationalOrganization
#     local_business_type: ''
#     org_name: Ecology of Marine Microbes
#     description: Ecology of Marine Microbes Group at Institut de Ciències del Mar (ICM-CSIC)
#     twitter: EMM_Barcelona
  # analytics:
  #   google_analytics: ''
  #   baidu_tongji: ''
  #   google_tag_manager: ''
  #   microsoft_clarity: ''
  # verification:
  #   google: ''
  #   baidu: ''

# Site header

header:
  navbar:
    enable: true
    blox: "navbar"
    align: r
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true


# Site footer
footer:
#    block: "custom-footer" # Use the custom footer block globally
  copyright:
    notice: '© {year} EMM (ICM-CSIC). This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false


# Contact (edit or remove options as required)
#email: mail@icm.csic.es
phone: +34 93 230 95 00
address:
  street: Passeig Marítim de la Barceloneta 37-49
  city: Barcelona
  region: Catalonia, Spain
  postcode: '08003'
  country: Spain
  country_code: ES
coordinates:
  latitude: '41.38529870028162'
  longitude: '2.1963520523517723'
directions: The (sometimes) beautiful Somorrostro beach
#office_hours:
#  - 'Monday 10:00 to 13:00'
#  - 'Wednesday 09:00 to 10:00'
#appointment_url: 'https://calendly.com'
contact_links:
  - icon: twitter
    icon_pack: fab
    name: Twitter
    link: 'https://twitter.com/EMM_Barcelona'
  #- icon: skype
  #  icon_pack: fab
  #  name: Skype Me
  #  link: 'skype:skype_id;'
  #- icon: keybase
  #  icon_pack: fab
  #  name: Chat on Keybase
  #  link: 'https://keybase.io/'
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Extensions

extensions:
  decap_cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Citation style

publications:
  date_format: January 2006
  citation_style: apa



# parameters
params:
authors:
  - name: 'Albert Bosch'
    slug: 'albert-bosch'
  - name: 'Aleix Obiol'
    slug: 'aleix-obiol'
  - name: 'Ana Manrique-Hernández'
    slug: 'ana-manrique-hernandez'
  - name: 'Andrea G. Bravo'
    slug: 'andrea-g\.-bravo'
  - name: 'Arne Bratvić'
    slug: 'arne-bratvic'
  - name: 'Carla Pereira García'
    slug: 'carla-pereira-garcia'
  - name: 'Carlos Pedrós-Alió'
    slug: 'carlos-pedros-alio'
  - name: 'Caterina R. Giner'
    slug: 'caterina-r\.-giner'
  - name: 'Celine Lavergne'
    slug: 'celine-lavergne'
  - name: 'Cinthya Vieyra'
    slug: 'cinthya-vieyra'
  - name: 'Clara Cardelús'
    slug: 'clara-cardelus'
  - name: 'Clara Ruiz-González'
    slug: 'clara-ruiz-gonzalez'
  - name: 'Clàudia González-Valdivia'
    slug: 'claudia-gonzalez-valdivia'
  - name: 'Dani Romano'
    slug: 'daniel-romano-gude'
  - name: 'David Pere Arnal Borràs'
    slug: 'david-pere-arnal-borras'
  - name: 'Dolors Vaqué'
    slug: 'dolors-vaque'
  - name: 'Elena Cerdán-García'
    slug: 'elena-cerdan-garcia'
  - name: 'Elisabet L. Sà'
    slug: 'elisabet-l\.-sa'
  - name: 'Ester María López-García'
    slug: 'ester-maría-lópez-garcía'
  - name: 'Felipe H. Coutinho'
    slug: 'felipe-h\.-coutinho'
  - name: 'Francesco Colizzi'
    slug: 'francesco-colizzi'
  - name: 'Francisco Latorre'
    slug: 'francisco-latorre'
  - name: 'Francisco M. Cornejo-Castillo'
    slug: 'francisco-m\.-cornejo-castillo'
  - name: 'Gemma Casas'
    slug: 'gemma-casas'
  - name: 'Georgina L. Brennan'
    slug: 'georgina-l\.-brennan'
  - name: 'Guillem Marimon'
    slug: 'guillem-marimon'
  - name: 'Irene Forn'
    slug: 'irene-forn'
  - name: 'Isabel Ferrera'
    slug: 'isabel-ferrera'
  - name: 'Isabel Gómez-Martos'
    slug: 'isabel-gomez-martos'
  - name: 'Javier del Campo'
    slug: 'javier-del-campo'
  - name: 'Jonah Díaz-Cruz'
    slug: 'jonah-diaz-cruz'
  - name: 'Josep M. Gasol'
    slug: 'josep-m\.-gasol'
  - name: 'Judith Traver Azuara'
    slug: 'judith-traver-azuara'
  - name: 'Júlia Dordal-Soriano'
    slug: 'julia-dordal-soriano'
  - name: 'Laura Cabrera-Vázquez'
    slug: 'laura-cabrera-vazquez'
  - name: 'Lidia Montiel'
    slug: 'lidia-montiel'
  - name: 'Maria Montserrat Sala'
    slug: 'maria-montserrat-sala'
  - name: 'Maria Sierks'
    slug: 'maria-sierks'
  - name: 'Marta Sebastián'
    slug: 'marta-sebastian'
  - name: 'Massimo C. Pernice'
    slug: 'massimo-c\.-pernice'
  - name: 'Mattia Greco'
    slug: 'mattia-greco'
  - name: 'Mohammad-Binsarhan'
    slug: 'mohammad-binsarhan'
  - name: 'Néstor Arandia-Gorostidi'
    slug: 'nestor-arandia-gorostidi'
  - name: 'Olga Sánchez'
    slug: 'olga-sanchez'
  - name: 'Ona Deulofeu'
    slug: 'ona-deulofeu'
  - name: 'Pablo Sánchez'
    slug: 'pablo-sanchez'
  - name: 'Paula Sabaté Fàbregas'
    slug: 'paula-sabate-fabregas'
  - name: 'Pierre Ramond'
    slug: 'pierre-ramond'
  - name: 'Raimon Bundó'
    slug: 'raimon-bundo'
  - name: 'Ramiro Logares'
    slug: 'ramiro-logares'
  - name: 'Ramon Massana'
    slug: 'ramon-massana'
  - name: 'Sandra Garcés-Pastor'
    slug: 'sandra-garces-pastor'
  - name: 'Sergi Martorell-Borrás'
    slug: 'sergi-martorell-borras'
  - name: 'Sergio González Motos'
    slug: 'sergio-gonzalez-motos'
  - name: 'Silvia G. Acinas'
    slug: 'silvia-g\.-acinas'
  - name: 'Sofiya Bondarenko'
    slug: 'sofiya-bondarenko'
  - name: 'Stefania Di Pede Mattatelli'
    slug: 'ania-di-pede'
  - name: 'Teresa Porta'
    slug: 'teresa-porta'
  - name: 'Ulises Lora'
    slug: 'ulises-lora'
  - name: 'Vanessa Balagué'
    slug: 'vanessa-balague'
  - name: 'Viena Puigcorbé'
    slug: 'viena-puigcorbe'
  - name: 'Xabier López-Alforja'
    slug: 'xabier-lopez-alforja'
  - name: 'Xavier Rey Velasco'
    slug: 'xavier-rey-velasco'
